services:
  
  mysql:
    image: mysql:9.7.0
    container_name: mysql
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD_FILE: /run/secrets/db_password #Hasło dostępowe do roota jest przekazywane z użyciem secrets
    secrets:
      - db_password
    volumes:
      - mysql-data:/var/lib/mysql # Nazwany wolumen do przechowywania zawartości baz danych
    networks:
      - back

  php-app:
    build: .
    container_name: php-app
    restart: unless-stopped
    secrets:
      - db_password # Aplikacja też potrzebuje hasła aby połączyć się z mysql
    volumes:
      - ./html:/var/www/html
    networks:
      - back
    depends_on:
      - mysql

  phpmyadmin:
    image: phpmyadmin:fpm-alpine
    container_name: phpmyadmin
    restart: unless-stopped
    environment:
      - PMA_HOST=mysql
    volumes:
      - pma-html:/var/www/html
    networks:
      - back # phpmyadmin jest podłączony do sieci dla backendu
    depends_on:
      - mysql

  nginx:
    image: nginx:1.31.1-alpine
    container_name: nginx
    restart: unless-stopped
    volumes:
      - pma-html:/var/www/pma-html:ro # Nginx ma dostęp do plików źródłowych phpmyadmin (read only)
      - ./html:/var/www/html
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
    networks:
      - front
      - back
    ports:
      - 4001:4001
      - 6001:6001
    expose:
      - 4001 # Informacja o przekierowaniu portów do dokumentacji
      - 6001
    depends_on:
      - php-app
      - phpmyadmin

volumes:
  mysql-data:
  pma-html:

networks:
  
  front:
    driver: bridge
  
  back:
    driver: bridge
    internal: true # Kontenery z tej sieci nie mogą się komunikować ze światem zewnętrzym (host nie tworzy reguł NAT dla tej sieci)

secrets:
  db_password:
    file: ./db_password.txt